apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selfSigned: {}
environment:
PATH: /snap/bin:{{ ansible_env.PATH }}
